# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Build with Ant
      run: javac src/Main.java -d out

    - name: Rodando Programa
      run: java -cp out Main

    - name: mensagem de sucesso
      run: echo DEU GREEEEEEEEEEEEEEEEEEEEEEEEEEEEENNNNNNNNNNNN!!!!!!!

    - uses: mr-smithers-excellent/docker-build-push@v6.4
      name: Docker Build & Push Action
        with:
          image: : repo/image
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
